New users list design + search + scrolling
Glimesh/glimesh.tv pull request #294
Opened 2020-12-12 02:13 UTC by clone1018

![image](https://user-images.githubusercontent.com/226638/101969962-7d4a9c00-3bf5-11eb-8693-72caf200f35d.png)

2020-12-12 02:47 UTC, clone1018 commented on lib/glimesh_web/uploaders/avatar.ex
> +    "https://www.gravatar.com/avatar/#{hash}?s=200&d=robohash"
Also implements Gravatar for users without avatars :)

2020-12-13 21:36 UTC, mja00 requested changes
Just two things to ignore banned users from the user listing

2020-12-13 21:36 UTC, mja00 commented on lib/glimesh/accounts.ex
> +    Repo.all(from(u in User))
```suggestion
    Repo.all(from u in User, where: u.is_banned == false)
```
This'll make it skip over any globally banned users

2020-12-13 21:36 UTC, mja00 commented on lib/glimesh/accounts.ex
> +        where: ilike(u.username, ^like),
```suggestion
        where: ilike(u.username, ^like),
        where: u.is_banned == false,
```

2020-12-13 22:09 UTC, merged