Adding new DMCA Policy page
Glimesh/glimesh.tv pull request #362
Opened 2021-01-10 02:11 UTC by clone1018

![screencapture-glimesh-dev-about-dmca-1610244657724](https://user-images.githubusercontent.com/226638/104112631-35379b80-52bf-11eb-8851-87fae4458cec.png)

2021-01-10 04:01 UTC, Heiwa1580 requested changes
Sentence structure in some areas should be improved. Also some grammer errors.

Also if we are looking at this sort of format it may be nice to beef up some of the explanations just a little to make it more in line. For example it mentions nothing about the timelines of our takedowns or the timeline of the counter notices or anything about a repeat infringer policy.

2021-01-10 12:32 UTC, clone1018 commented
You should be able to make revisions directly in the Files Changed tabs, it'll be easier on a desktop though :)

2021-01-10 13:36 UTC, Heiwa1580 commented
> You should be able to make revisions directly in the Files Changed tabs, it'll be easier on a desktop though :)

Haha yeah when I find the time I will for sure.

2021-01-12 21:49 UTC, Heiwa1580 commented on lib/glimesh_web/templates/about/dmca.html.eex
> +                            <%= gettext("Glimesh is also working towards developing ideas where we can either satisfy licensing requirements.") %>
```suggestion
                            <%= gettext("Lastly Glimesh is working to partner with music providers or independant artists who will provide properly licensed music for you to use.") %>
```

2021-01-12 21:51 UTC, Heiwa1580 commented on lib/glimesh_web/templates/about/dmca.html.eex
> +                        <%= gettext("Copyrights are protections given to creative works and their owners. You can simply think of copyrights as the right to copy a creative work. As the owner of a cr
```suggestion
                        <%= gettext("Copyrights are protections given to creative works and their owners. You can simply think of copyrights as the right to copy a creative work. As the owner of a creative work you have the right to copy that work in any way you'd like and copyright laws like the DMCA protect you from anyone else copying that work without your permission. Copyrights are actually given to you as the owner the moment you create a work. By default the law gives you some basic copyrights the moment you create an original work registering your work online just makes it easier to protect but creative works are instantly protected by Copyright laws.") %>
```

2021-01-12 21:55 UTC, Heiwa1580 commented on lib/glimesh_web/templates/about/dmca.html.eex
> +                            <%= gettext("Glimesh will be fully transparent about DMCA Takedown requests. The whole community will see the requests and will be able to respond to them. So false reques
```suggestion
                            <%= gettext("Glimesh will be fully transparent about DMCA Takedown requests. The whole community will see the requests and will be able to respond to them. So false requests will have little effectiveness and the community as a whole will be able to combat them together. ") %>
```

2021-01-12 23:12 UTC, merged