Current Homepage Channels Query
Glimesh/glimesh.tv pull request #748
Opened 2021-08-30 11:10 UTC by ponkey364

(fyi, this is the first bit of elixr I've ever written, although it's mostly a copy/paste job from other queries)

Done off the back of #719, with the aim of going in and implementing the homepage streams list in the mobile app.

For the most part, I looked at how the other queries work, especially the categories query, so I think it *should* be in line with what's expected here.

I just used a `[Channel]` rather than a connection because I didn't see the point in setting it up for 6 streams

2021-08-30 12:45 UTC, clone1018 commented
Thanks for the PR! Looks good so far. 

> I just used a `[Channel]` rather than a connection because I didn't see the point in setting it up for 6 streams

Let's use a connection anyway, as we continue to grow out the homepage we don't want to introduce breaking changes to the API just to add more streams :P. This is what got us into trouble with the first API.

2021-08-30 15:16 UTC, ponkey364 commented
I think that this attempt should be better, it has a connection now

2021-09-03 13:42 UTC, clone1018 requested changes
Tested it locally, works great! Ready to merge after a couple of nitpicks. Thanks again!

2021-09-03 13:42 UTC, clone1018 commented on lib/glimesh/api/schema/channel_types.ex
> +    connection field :homepage, node_type: :channel do
```suggestion
    connection field :homepage_channels, node_type: :channel do
```

2021-09-03 13:42 UTC, clone1018 commented on lib/glimesh/api/resolvers/channel_resolver.ex
> +  def list_homepage_streams(args, _) do
```suggestion
  def list_homepage_channels(args, _) do
```

2021-09-03 13:42 UTC, clone1018 commented on lib/glimesh/api/schema/channel_types.ex
> +      resolve(&ChannelResolver.list_homepage_streams/2)
```suggestion
      resolve(&ChannelResolver.list_homepage_channels/2)
```

2021-09-04 10:57 UTC, merged